version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # args:
      #   NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${NEXT_PUBLIC_GRAPHQL_ENDPOINT}
      #   NEXT_PUBLIC_MINI_APP_LINK: ${NEXT_PUBLIC_MINI_APP_LINK}
      #   GRAPHQL_SERVER_ENDPOINT: http://backend:3001/graphql
    image: "frontend"
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    tty: true
